---
svn:
  executable_path: "/usr/bin/svn"
  host:
  user:
  password:
clash_check:
  last_run_revision:
  project_url:
  non_project_url:
diff_check:
  source_url:
  branched_url:
keyword_check:
  run_remote: true
  svn_url:
  files:
  - ".ksh"
  - ".sh"
  - ".ddl"
  - ".sql"
  - ".pls"
  - ".pks"
  - ".pkb"
  - ".java"
