# svn
svn:
 executable_path: /usr/bin/svn
 host: svn://hostname
 user: svn_user
 password: svn_password
 branch_url: svn://hostname/trunk
 keywords_files:
 - '.ksh'
 - '.sh'
 - '.ddl'
 - '.sql'
 - '.pls'
 - '.pks'
 - '.pkb'
 - '.java'


